# Generated by Django 5.1.3 on 2024-12-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursesection_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_section_images/'),
        ),
    ]
