# Generated by Django 5.1.3 on 2024-12-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursesection_pdf_file_coursetest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='pdf_file',
        ),
    ]
