# Generated by Django 5.1.3 on 2024-12-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_coursesection_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
