# Generated by Django 5.1.4 on 2024-12-27 05:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursesection_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='additional_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
