# Generated by Django 5.1.4 on 2025-01-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='max_tests_per_course',
        ),
        migrations.AddField(
            model_name='settings',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='max_tests_per_user',
            field=models.PositiveIntegerField(default=10, verbose_name='Foydalanuvchi uchun maksimal testlar soni'),
        ),
    ]
