# Generated by Django 5.1.4 on 2025-01-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_settings_max_tests_per_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={},
        ),
        migrations.AlterField(
            model_name='settings',
            name='max_tests_per_user',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
