# Generated by Django 5.1.4 on 2025-01-11 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_settings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('easy', 'Oson'), ('medium', 'O‘rtacha'), ('hard', 'Qiyin')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='coursesection',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty_level',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.difficultylevel'),
            preserve_default=False,
        ),
    ]
