# Generated by Django 5.1.4 on 2025-01-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_difficultylevel_coursesection_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='requires_completion',
            field=models.BooleanField(default=False),
        ),
    ]
