# Generated by Django 5.1.4 on 2025-01-21 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_coursesectionprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtuallabresult',
            name='test',
        ),
        migrations.RemoveField(
            model_name='virtuallabresult',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='coursesectionprogress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='requires_completion',
        ),
        migrations.AddField(
            model_name='settings',
            name='max_tests_per_course',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddConstraint(
            model_name='coursesectionprogress',
            constraint=models.UniqueConstraint(fields=('user', 'section'), name='unique_section_progress_per_user'),
        ),
        migrations.DeleteModel(
            name='VirtualLabResult',
        ),
    ]
