# Generated by Django 5.1.4 on 2025-01-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_virtuallabresult_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
