# Generated by Django 5.1.4 on 2025-01-25 11:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_quiz_quizquestion_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
